### ISSUE TITLE
ტექსტში სასვენი ნიშნების გაასწორებისას ტესტები აღარ მუშაობს

### ISSUE THREAD

**Issue by LukeSamkharadze** [freeuni-paradigms/assignment-1-rsg#3]
ძაან ცუდი ტესტებია, ყველა სასვენი ნიშნის წინ **სპეისი** გავასწორე და არ გადიოდა ტესტებს.

მერე აღმოვაჩინე რო ტესტების ბრალი იყო. 

აქ მაგალითად ("?"):
```
Bill gates Does it Again! Have you ever wanted to
go spelunking on the lunatic fringe ? Microsoft announces
MS-DOS 0.0.0.1r for Windows.
```

**Comment by iarigby** [comment]
?-მდე რომ სფეისი არის მაგის?

**Comment by LukeSamkharadze** [comment]
კი სპეისები

**Comment by iarigby** [comment]
ჩავამატებ ინსტრუქციაში, რომ ამ ტესტერზე სასვენი ნიშნების წინ აუცილებელია space-ის დაწერა

**Comment by tsakh** [comment]
სასვენი ნიშნების წინ სფეისები ხელით უნდა ჩავუწეროთ ანუ? მე არ ჩამიწერია და ტესტებზე გადის მაინც და შეიძლება ჩვენ რა ტესტებიც გვაქვს მაგაზე გადიოდეს მაგრამ შეცდომა იყოს?

**Comment by iarigby** [comment]
არ უნდა ჩაწეროთ. ვინც დაამატა მაგის შემოწმება და სფეისის გამოტოვება,
პრობლემა შეექმნათ ტესტებზე.

**Comment by tsakh** [comment]
გასაგებია, დიდი მადლობა.
