### ISSUE TITLE
bsearch

### ISSUE THREAD

**Issue by tsakh** [freeuni-paradigms/assignment-1-rsg#7]
ორობითი ძებნის ალგორითმი დავწერე და მერე ვნახე რომ უკვე დაწერილის გამოყენებაა რეკომენდირებული. ეს bsearch ელემენტის ზომას იღებს არგუმენტად და ჩვენს მასივში ხომ სხვადასხვა სიგრძისაა სტრინგები. მაგან დამაბნია, ვერ ვხვდები როგორ უნდა გამოვიყენო და არასწორად ხომ არ მესმის საერთოდ?

**Comment by d-chechelashvili** [comment]
მეორე დავალების კითხვაა ეს ხომ აშკარად? :დ
